port: "13002"
SECRET_KEY: pR7MOPjc71dQcCQSJmplMe0PDukBpzTn
AdminPWD: 
FormMemory: 256
Database:
  Username: acc_manage
  Password: aaa123123
  DBType: sqlite
  DBHost: localhost
  DBProt: "5432"
  DBName: acc_Manage
UsersApi:
  port: "13003"
  SECRET_KEY: N0MTsBEsh7DsXcqr5cgj6e0rAAEFP2cX
Redis:
  Host: 192.168.1.90:6379
  Password: zH05aXvMzFpy8vDY
  DB: 1
