port: "13002"
SECRET_KEY: IusQKoWQYZ9pReWDyFD5K5kl2nUj2bOn
AdminPWD: gzgbrsbZ0p0x
FormMemory: 256
Database:
  Username: acc_manage
  Password: aaa123123
  DBType: sqlite
  DBHost: localhost
  DBProt: "5432"
  DBName: acc_Manage
UsersApi:
  port: "13003"
  SECRET_KEY: NAsUng5HdjVwMuppRSofRppf7xnPm62y
Redis:
  Host: localhost:6379
  Password: 3SuLc0VvzLJm
  DB: 1
