// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCart(arg1:Array<number>):Promise<{[key: string]: any}>;

export function CheckLogin():Promise<{[key: string]: any}>;

export function CleanCart():Promise<{[key: string]: any}>;

export function DeleteCart(arg1:number):Promise<{[key: string]: any}>;

export function FormatDateTime(arg1:number):Promise<string>;

export function GetCart():Promise<{[key: string]: any}>;

export function GetGamesList():Promise<{[key: string]: any}>;

export function GetOrdersDetail(arg1:{[key: string]: any}):Promise<{[key: string]: any}>;

export function GetOrdersList(arg1:{[key: string]: any}):Promise<{[key: string]: any}>;

export function GetProducts(arg1:{[key: string]: any}):Promise<{[key: string]: any}>;

export function GetUsers():Promise<{[key: string]: any}>;

export function Login(arg1:{[key: string]: any}):Promise<{[key: string]: any}>;

export function Logout():Promise<{[key: string]: any}>;

export function OrderRefund(arg1:{[key: string]: any}):Promise<{[key: string]: any}>;

export function PostOrders(arg1:Array<number>):Promise<{[key: string]: any}>;
