// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccountRefund(arg1) {
  return window['go']['main']['App']['AccountRefund'](arg1);
}

export function AddCart(arg1) {
  return window['go']['main']['App']['AddCart'](arg1);
}

export function Captcha() {
  return window['go']['main']['App']['Captcha']();
}

export function CheckLogin() {
  return window['go']['main']['App']['CheckLogin']();
}

export function CleanCart() {
  return window['go']['main']['App']['CleanCart']();
}

export function DeleteCart(arg1) {
  return window['go']['main']['App']['DeleteCart'](arg1);
}

export function FormatDateTime(arg1) {
  return window['go']['main']['App']['FormatDateTime'](arg1);
}

export function GetCart() {
  return window['go']['main']['App']['GetCart']();
}

export function GetGamesList() {
  return window['go']['main']['App']['GetGamesList']();
}

export function GetLedger(arg1) {
  return window['go']['main']['App']['GetLedger'](arg1);
}

export function GetOrdersDetail(arg1) {
  return window['go']['main']['App']['GetOrdersDetail'](arg1);
}

export function GetOrdersList(arg1) {
  return window['go']['main']['App']['GetOrdersList'](arg1);
}

export function GetProducts(arg1) {
  return window['go']['main']['App']['GetProducts'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OrderRefund(arg1) {
  return window['go']['main']['App']['OrderRefund'](arg1);
}

export function PostOrders(arg1) {
  return window['go']['main']['App']['PostOrders'](arg1);
}

export function Regedit(arg1) {
  return window['go']['main']['App']['Regedit'](arg1);
}

export function SearchProducts(arg1) {
  return window['go']['main']['App']['SearchProducts'](arg1);
}
