// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccountRefund(arg1) {
  return window['go']['main']['App']['AccountRefund'](arg1);
}

export function CheckAdminID() {
  return window['go']['main']['App']['CheckAdminID']();
}

export function CheckLogin() {
  return window['go']['main']['App']['CheckLogin']();
}

export function FormatDateTime(arg1) {
  return window['go']['main']['App']['FormatDateTime'](arg1);
}

export function GetAdmin() {
  return window['go']['main']['App']['GetAdmin']();
}

export function GetGamesList() {
  return window['go']['main']['App']['GetGamesList']();
}

export function GetLedger(arg1) {
  return window['go']['main']['App']['GetLedger'](arg1);
}

export function GetOrdersDetail(arg1) {
  return window['go']['main']['App']['GetOrdersDetail'](arg1);
}

export function GetOrdersList(arg1) {
  return window['go']['main']['App']['GetOrdersList'](arg1);
}

export function GetProducts(arg1) {
  return window['go']['main']['App']['GetProducts'](arg1);
}

export function GetUserWithKey(arg1) {
  return window['go']['main']['App']['GetUserWithKey'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OrderRefund(arg1) {
  return window['go']['main']['App']['OrderRefund'](arg1);
}

export function RePassword(arg1) {
  return window['go']['main']['App']['RePassword'](arg1);
}

export function SendCoinToUser(arg1) {
  return window['go']['main']['App']['SendCoinToUser'](arg1);
}

export function TransferUseWallet(arg1) {
  return window['go']['main']['App']['TransferUseWallet'](arg1);
}
