port: "13002"
SECRET_KEY: yf9CowCCf3FZLnkGrrCs449n152UXvJT
AdminPWD: ""
GlobalToken: QZ1DUua0gkr1lLw3BAoGJOlPIHkhNoqC
Username: ""
Password: ""
Database:
  DBType: ""
  DBHost: ""
  DBProt: ""
  DBName: ""
UsersApi:
  port: "13003"
  SECRET_KEY: s9oV39FEtQ4A2cHN3AU2dRFDpegaEVgL
Redis:
  Host: 127.0.0.1:6379
  Password: 3SuLc0VvzLJm
  DB: 1
